name: .NET

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Display .NET Info
        run: dotnet --info

      - name: Restore Dependencies
        run: dotnet restore FileHubOrg.sln

      - name: Build Solution
        run: dotnet build FileHubOrg.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test FileHubOrg.sln --configuration Release --no-build --verbosity normal
